[package]
name = "baccounts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgp = "0.10"
log = "*"
env_logger = "*"
clap = { version = "*", features=["derive"] }