name: Baccounts v1 testing

on:
    push:
        paths:
            - 'v1/**'
            - '.github/workflows/v1.yml'


jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: v1
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: 1.21

            - name: Build
              run: go build ./...

            - name: Test
              run: go test -v ./...
